/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DriverAccountRouteImport } from './routes/driver-account'
import { Route as DriverEarningsRouteImport } from './routes/driver-earnings'
import { Route as DriverMapRouteImport } from './routes/driver-map'
import { Route as DriverTasksRouteImport } from './routes/driver-tasks'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as MapRouteImport } from './routes/map'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProviderFinanceRouteImport } from './routes/provider-finance'
import { Route as ProviderInsightsRouteImport } from './routes/provider-insights'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RequestAnythingRouteImport } from './routes/request-anything'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as SetupTestAccountsRouteImport } from './routes/setup-test-accounts'
import { Route as SpecialDeliveryRouteImport } from './routes/special-delivery'
import { Route as TaxiRouteImport } from './routes/taxi'
import { Route as VerifyPhoneRouteImport } from './routes/verify-phone'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCourierRouteImport } from './routes/admin.courier'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSettlementsRouteImport } from './routes/admin.settlements'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as AdsIdRouteImport } from './routes/ads.$id'
import { Route as AdsNewRouteImport } from './routes/ads.new'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as JoinDriverRouteImport } from './routes/join.driver'
import { Route as JoinProviderRouteImport } from './routes/join.provider'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as PharmaciesIndexRouteImport } from './routes/pharmacies.index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as ServiceRequestsIndexRouteImport } from './routes/service-requests.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as ApiPublicAdImageSplatRouteImport } from './routes/api/public/ad-image.$'
import { Route as ApiPublicPaymentsStripeRouteImport } from './routes/api/public/payments.stripe'
import { Route as ApiPublicProviderImageSplatRouteImport } from './routes/api/public/provider-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAccountRoute = DriverAccountRouteImport.update({
  id: '/driver-account',
  path: '/driver-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver-earnings',
  path: '/driver-earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverMapRoute = DriverMapRouteImport.update({
  id: '/driver-map',
  path: '/driver-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTasksRoute = DriverTasksRouteImport.update({
  id: '/driver-tasks',
  path: '/driver-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFinanceRoute = ProviderFinanceRouteImport.update({
  id: '/provider-finance',
  path: '/provider-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderInsightsRoute = ProviderInsightsRouteImport.update({
  id: '/provider-insights',
  path: '/provider-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAnythingRoute = RequestAnythingRouteImport.update({
  id: '/request-anything',
  path: '/request-anything',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTestAccountsRoute = SetupTestAccountsRouteImport.update({
  id: '/setup-test-accounts',
  path: '/setup-test-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialDeliveryRoute = SpecialDeliveryRouteImport.update({
  id: '/special-delivery',
  path: '/special-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiRoute = TaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/admin/courier',
  path: '/admin/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/admin/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/admin/sections',
  path: '/admin/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIdRoute = AdsIdRouteImport.update({
  id: '/ads/$id',
  path: '/ads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsNewRoute = AdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDriverRoute = JoinDriverRouteImport.update({
  id: '/join/driver',
  path: '/join/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProviderRoute = JoinProviderRouteImport.update({
  id: '/join/provider',
  path: '/join/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/marketplace/new',
  path: '/marketplace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesIndexRoute = PharmaciesIndexRouteImport.update({
  id: '/pharmacies/',
  path: '/pharmacies/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsIndexRoute = ServiceRequestsIndexRouteImport.update({
  id: '/service-requests/',
  path: '/service-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdImageSplatRoute = ApiPublicAdImageSplatRouteImport.update({
  id: '/api/public/ad-image/$',
  path: '/api/public/ad-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsStripeRoute = ApiPublicPaymentsStripeRouteImport.update({
  id: '/api/public/payments/stripe',
  path: '/api/public/payments/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProviderImageSplatRoute =
  ApiPublicProviderImageSplatRouteImport.update({
    id: '/api/public/provider-image/$',
    path: '/api/public/provider-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-account': typeof DriverAccountRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/driver-map': typeof DriverMapRoute
  '/driver-tasks': typeof DriverTasksRoute
  '/family': typeof FamilyRoute
  '/guarantee': typeof GuaranteeRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plus': typeof PlusRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/provider-insights': typeof ProviderInsightsRoute
  '/quotes': typeof QuotesRoute
  '/referrals': typeof ReferralsRoute
  '/request-anything': typeof RequestAnythingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/pharmacies/': typeof PharmaciesIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/provider-image/$': typeof ApiPublicProviderImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-account': typeof DriverAccountRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/driver-map': typeof DriverMapRoute
  '/driver-tasks': typeof DriverTasksRoute
  '/family': typeof FamilyRoute
  '/guarantee': typeof GuaranteeRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plus': typeof PlusRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/provider-insights': typeof ProviderInsightsRoute
  '/quotes': typeof QuotesRoute
  '/referrals': typeof ReferralsRoute
  '/request-anything': typeof RequestAnythingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin': typeof AdminIndexRoute
  '/ads': typeof AdsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/pharmacies': typeof PharmaciesIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/service-requests': typeof ServiceRequestsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/provider-image/$': typeof ApiPublicProviderImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-account': typeof DriverAccountRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/driver-map': typeof DriverMapRoute
  '/driver-tasks': typeof DriverTasksRoute
  '/family': typeof FamilyRoute
  '/guarantee': typeof GuaranteeRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plus': typeof PlusRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/provider-insights': typeof ProviderInsightsRoute
  '/quotes': typeof QuotesRoute
  '/referrals': typeof ReferralsRoute
  '/request-anything': typeof RequestAnythingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/pharmacies/': typeof PharmaciesIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/provider-image/$': typeof ApiPublicProviderImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-account'
    | '/driver-earnings'
    | '/driver-map'
    | '/driver-tasks'
    | '/family'
    | '/guarantee'
    | '/map'
    | '/nearby'
    | '/notifications'
    | '/payments'
    | '/plus'
    | '/provider'
    | '/provider-finance'
    | '/provider-insights'
    | '/quotes'
    | '/referrals'
    | '/request-anything'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/welcome'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/map'
    | '/admin/marketplace'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/users'
    | '/admin/zones'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/marketplace/new'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/shops/$slug'
    | '/stores/$id'
    | '/admin/'
    | '/ads/'
    | '/doctors/'
    | '/marketplace/'
    | '/orders/'
    | '/pharmacies/'
    | '/restaurants/'
    | '/service-requests/'
    | '/services/'
    | '/shops/'
    | '/stores/'
    | '/api/public/maintenance'
    | '/api/public/push-dispatch'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
    | '/api/public/provider-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-account'
    | '/driver-earnings'
    | '/driver-map'
    | '/driver-tasks'
    | '/family'
    | '/guarantee'
    | '/map'
    | '/nearby'
    | '/notifications'
    | '/payments'
    | '/plus'
    | '/provider'
    | '/provider-finance'
    | '/provider-insights'
    | '/quotes'
    | '/referrals'
    | '/request-anything'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/welcome'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/map'
    | '/admin/marketplace'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/users'
    | '/admin/zones'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/marketplace/new'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/shops/$slug'
    | '/stores/$id'
    | '/admin'
    | '/ads'
    | '/doctors'
    | '/marketplace'
    | '/orders'
    | '/pharmacies'
    | '/restaurants'
    | '/service-requests'
    | '/services'
    | '/shops'
    | '/stores'
    | '/api/public/maintenance'
    | '/api/public/push-dispatch'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
    | '/api/public/provider-image/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-account'
    | '/driver-earnings'
    | '/driver-map'
    | '/driver-tasks'
    | '/family'
    | '/guarantee'
    | '/map'
    | '/nearby'
    | '/notifications'
    | '/payments'
    | '/plus'
    | '/provider'
    | '/provider-finance'
    | '/provider-insights'
    | '/quotes'
    | '/referrals'
    | '/request-anything'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/welcome'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/map'
    | '/admin/marketplace'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/users'
    | '/admin/zones'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/marketplace/new'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/shops/$slug'
    | '/stores/$id'
    | '/admin/'
    | '/ads/'
    | '/doctors/'
    | '/marketplace/'
    | '/orders/'
    | '/pharmacies/'
    | '/restaurants/'
    | '/service-requests/'
    | '/services/'
    | '/shops/'
    | '/stores/'
    | '/api/public/maintenance'
    | '/api/public/push-dispatch'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
    | '/api/public/provider-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  CheckoutRoute: typeof CheckoutRoute
  CourierRoute: typeof CourierRoute
  DriverRoute: typeof DriverRoute
  DriverAccountRoute: typeof DriverAccountRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverMapRoute: typeof DriverMapRoute
  DriverTasksRoute: typeof DriverTasksRoute
  FamilyRoute: typeof FamilyRoute
  GuaranteeRoute: typeof GuaranteeRoute
  MapRoute: typeof MapRoute
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PlusRoute: typeof PlusRoute
  ProviderRoute: typeof ProviderRoute
  ProviderFinanceRoute: typeof ProviderFinanceRoute
  ProviderInsightsRoute: typeof ProviderInsightsRoute
  QuotesRoute: typeof QuotesRoute
  ReferralsRoute: typeof ReferralsRoute
  RequestAnythingRoute: typeof RequestAnythingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SetupTestAccountsRoute: typeof SetupTestAccountsRoute
  SpecialDeliveryRoute: typeof SpecialDeliveryRoute
  TaxiRoute: typeof TaxiRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdsIdRoute: typeof AdsIdRoute
  AdsNewRoute: typeof AdsNewRoute
  JoinDriverRoute: typeof JoinDriverRoute
  JoinProviderRoute: typeof JoinProviderRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  StoresIdRoute: typeof StoresIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdsIndexRoute: typeof AdsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PharmaciesIndexRoute: typeof PharmaciesIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
  ServiceRequestsIndexRoute: typeof ServiceRequestsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicAdImageSplatRoute: typeof ApiPublicAdImageSplatRoute
  ApiPublicPaymentsStripeRoute: typeof ApiPublicPaymentsStripeRoute
  ApiPublicProviderImageSplatRoute: typeof ApiPublicProviderImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-account': {
      id: '/driver-account'
      path: '/driver-account'
      fullPath: '/driver-account'
      preLoaderRoute: typeof DriverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-earnings': {
      id: '/driver-earnings'
      path: '/driver-earnings'
      fullPath: '/driver-earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-map': {
      id: '/driver-map'
      path: '/driver-map'
      fullPath: '/driver-map'
      preLoaderRoute: typeof DriverMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-tasks': {
      id: '/driver-tasks'
      path: '/driver-tasks'
      fullPath: '/driver-tasks'
      preLoaderRoute: typeof DriverTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-finance': {
      id: '/provider-finance'
      path: '/provider-finance'
      fullPath: '/provider-finance'
      preLoaderRoute: typeof ProviderFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-insights': {
      id: '/provider-insights'
      path: '/provider-insights'
      fullPath: '/provider-insights'
      preLoaderRoute: typeof ProviderInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-anything': {
      id: '/request-anything'
      path: '/request-anything'
      fullPath: '/request-anything'
      preLoaderRoute: typeof RequestAnythingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-test-accounts': {
      id: '/setup-test-accounts'
      path: '/setup-test-accounts'
      fullPath: '/setup-test-accounts'
      preLoaderRoute: typeof SetupTestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-delivery': {
      id: '/special-delivery'
      path: '/special-delivery'
      fullPath: '/special-delivery'
      preLoaderRoute: typeof SpecialDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi': {
      id: '/taxi'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-phone': {
      id: '/verify-phone'
      path: '/verify-phone'
      fullPath: '/verify-phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/admin/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/admin/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$id': {
      id: '/ads/$id'
      path: '/ads/$id'
      fullPath: '/ads/$id'
      preLoaderRoute: typeof AdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/new': {
      id: '/ads/new'
      path: '/ads/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/driver': {
      id: '/join/driver'
      path: '/join/driver'
      fullPath: '/join/driver'
      preLoaderRoute: typeof JoinDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/provider': {
      id: '/join/provider'
      path: '/join/provider'
      fullPath: '/join/provider'
      preLoaderRoute: typeof JoinProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies/': {
      id: '/pharmacies/'
      path: '/pharmacies'
      fullPath: '/pharmacies/'
      preLoaderRoute: typeof PharmaciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests/': {
      id: '/service-requests/'
      path: '/service-requests'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof ServiceRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-image/$': {
      id: '/api/public/ad-image/$'
      path: '/api/public/ad-image/$'
      fullPath: '/api/public/ad-image/$'
      preLoaderRoute: typeof ApiPublicAdImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/stripe': {
      id: '/api/public/payments/stripe'
      path: '/api/public/payments/stripe'
      fullPath: '/api/public/payments/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-image/$': {
      id: '/api/public/provider-image/$'
      path: '/api/public/provider-image/$'
      fullPath: '/api/public/provider-image/$'
      preLoaderRoute: typeof ApiPublicProviderImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  CheckoutRoute: CheckoutRoute,
  CourierRoute: CourierRoute,
  DriverRoute: DriverRoute,
  DriverAccountRoute: DriverAccountRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverMapRoute: DriverMapRoute,
  DriverTasksRoute: DriverTasksRoute,
  FamilyRoute: FamilyRoute,
  GuaranteeRoute: GuaranteeRoute,
  MapRoute: MapRoute,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PlusRoute: PlusRoute,
  ProviderRoute: ProviderRoute,
  ProviderFinanceRoute: ProviderFinanceRoute,
  ProviderInsightsRoute: ProviderInsightsRoute,
  QuotesRoute: QuotesRoute,
  ReferralsRoute: ReferralsRoute,
  RequestAnythingRoute: RequestAnythingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupAdminRoute: SetupAdminRoute,
  SetupTestAccountsRoute: SetupTestAccountsRoute,
  SpecialDeliveryRoute: SpecialDeliveryRoute,
  TaxiRoute: TaxiRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMapRoute: AdminMapRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdsIdRoute: AdsIdRoute,
  AdsNewRoute: AdsNewRoute,
  JoinDriverRoute: JoinDriverRoute,
  JoinProviderRoute: JoinProviderRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
  OrdersIdRoute: OrdersIdRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  StoresIdRoute: StoresIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdsIndexRoute: AdsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PharmaciesIndexRoute: PharmaciesIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
  ServiceRequestsIndexRoute: ServiceRequestsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicAdImageSplatRoute: ApiPublicAdImageSplatRoute,
  ApiPublicPaymentsStripeRoute: ApiPublicPaymentsStripeRoute,
  ApiPublicProviderImageSplatRoute: ApiPublicProviderImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
