/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as JoinProviderRouteImport } from './routes/join.provider'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProviderRoute = JoinProviderRouteImport.update({
  id: '/join/provider',
  path: '/join/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRoute
  '/provider': typeof ProviderRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRoute
  '/provider': typeof ProviderRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/orders': typeof OrdersIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRoute
  '/provider': typeof ProviderRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/driver'
    | '/provider'
    | '/admin/providers'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/stores/$id'
    | '/orders/'
    | '/restaurants/'
    | '/stores/'
    | '/api/public/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/driver'
    | '/provider'
    | '/admin/providers'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/stores/$id'
    | '/orders'
    | '/restaurants'
    | '/stores'
    | '/api/public/maintenance'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/driver'
    | '/provider'
    | '/admin/providers'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/stores/$id'
    | '/orders/'
    | '/restaurants/'
    | '/stores/'
    | '/api/public/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DriverRoute: typeof DriverRoute
  ProviderRoute: typeof ProviderRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  JoinProviderRoute: typeof JoinProviderRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  StoresIdRoute: typeof StoresIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/provider': {
      id: '/join/provider'
      path: '/join/provider'
      fullPath: '/join/provider'
      preLoaderRoute: typeof JoinProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DriverRoute: DriverRoute,
  ProviderRoute: ProviderRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  JoinProviderRoute: JoinProviderRoute,
  OrdersIdRoute: OrdersIdRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  StoresIdRoute: StoresIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
