/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DriverEarningsRouteImport } from './routes/driver-earnings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProviderFinanceRouteImport } from './routes/provider-finance'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as SetupTestAccountsRouteImport } from './routes/setup-test-accounts'
import { Route as SetupTestAdminRouteImport } from './routes/setup-test-admin'
import { Route as SpecialDeliveryRouteImport } from './routes/special-delivery'
import { Route as TaxiRouteImport } from './routes/taxi'
import { Route as VerifyPhoneRouteImport } from './routes/verify-phone'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCourierRouteImport } from './routes/admin.courier'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettlementsRouteImport } from './routes/admin.settlements'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as AdsIdRouteImport } from './routes/ads.$id'
import { Route as AdsNewRouteImport } from './routes/ads.new'
import { Route as JoinDriverRouteImport } from './routes/join.driver'
import { Route as JoinProviderRouteImport } from './routes/join.provider'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as ServiceRequestsIndexRouteImport } from './routes/service-requests.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'
import { Route as ApiPublicAdImageSplatRouteImport } from './routes/api/public/ad-image.$'
import { Route as ApiPublicPaymentsStripeRouteImport } from './routes/api/public/payments.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver-earnings',
  path: '/driver-earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFinanceRoute = ProviderFinanceRouteImport.update({
  id: '/provider-finance',
  path: '/provider-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTestAccountsRoute = SetupTestAccountsRouteImport.update({
  id: '/setup-test-accounts',
  path: '/setup-test-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTestAdminRoute = SetupTestAdminRouteImport.update({
  id: '/setup-test-admin',
  path: '/setup-test-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialDeliveryRoute = SpecialDeliveryRouteImport.update({
  id: '/special-delivery',
  path: '/special-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiRoute = TaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/admin/courier',
  path: '/admin/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIdRoute = AdsIdRouteImport.update({
  id: '/ads/$id',
  path: '/ads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsNewRoute = AdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDriverRoute = JoinDriverRouteImport.update({
  id: '/join/driver',
  path: '/join/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProviderRoute = JoinProviderRouteImport.update({
  id: '/join/provider',
  path: '/join/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsIndexRoute = ServiceRequestsIndexRouteImport.update({
  id: '/service-requests/',
  path: '/service-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdImageSplatRoute = ApiPublicAdImageSplatRouteImport.update({
  id: '/api/public/ad-image/$',
  path: '/api/public/ad-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsStripeRoute = ApiPublicPaymentsStripeRouteImport.update({
  id: '/api/public/payments/stripe',
  path: '/api/public/payments/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/setup-test-admin': typeof SetupTestAdminRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/ads/': typeof AdsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/setup-test-admin': typeof SetupTestAdminRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/ads': typeof AdsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/service-requests': typeof ServiceRequestsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/stores': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRoute
  '/driver': typeof DriverRoute
  '/driver-earnings': typeof DriverEarningsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/provider': typeof ProviderRoute
  '/provider-finance': typeof ProviderFinanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/setup-test-accounts': typeof SetupTestAccountsRoute
  '/setup-test-admin': typeof SetupTestAdminRoute
  '/special-delivery': typeof SpecialDeliveryRoute
  '/taxi': typeof TaxiRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads/$id': typeof AdsIdRoute
  '/ads/new': typeof AdsNewRoute
  '/join/driver': typeof JoinDriverRoute
  '/join/provider': typeof JoinProviderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/ads/': typeof AdsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/ad-image/$': typeof ApiPublicAdImageSplatRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-earnings'
    | '/notifications'
    | '/payments'
    | '/provider'
    | '/provider-finance'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/setup-test-admin'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settlements'
    | '/admin/users'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/stores/$id'
    | '/ads/'
    | '/orders/'
    | '/restaurants/'
    | '/service-requests/'
    | '/services/'
    | '/stores/'
    | '/api/public/maintenance'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-earnings'
    | '/notifications'
    | '/payments'
    | '/provider'
    | '/provider-finance'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/setup-test-admin'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settlements'
    | '/admin/users'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/stores/$id'
    | '/ads'
    | '/orders'
    | '/restaurants'
    | '/service-requests'
    | '/services'
    | '/stores'
    | '/api/public/maintenance'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/courier'
    | '/driver'
    | '/driver-earnings'
    | '/notifications'
    | '/payments'
    | '/provider'
    | '/provider-finance'
    | '/reset-password'
    | '/setup-admin'
    | '/setup-test-accounts'
    | '/setup-test-admin'
    | '/special-delivery'
    | '/taxi'
    | '/verify-phone'
    | '/wallet'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/courier'
    | '/admin/drivers'
    | '/admin/features'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settlements'
    | '/admin/users'
    | '/ads/$id'
    | '/ads/new'
    | '/join/driver'
    | '/join/provider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/services/$id'
    | '/stores/$id'
    | '/ads/'
    | '/orders/'
    | '/restaurants/'
    | '/service-requests/'
    | '/services/'
    | '/stores/'
    | '/api/public/maintenance'
    | '/api/public/ad-image/$'
    | '/api/public/payments/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CourierRoute: typeof CourierRoute
  DriverRoute: typeof DriverRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProviderRoute: typeof ProviderRoute
  ProviderFinanceRoute: typeof ProviderFinanceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SetupTestAccountsRoute: typeof SetupTestAccountsRoute
  SetupTestAdminRoute: typeof SetupTestAdminRoute
  SpecialDeliveryRoute: typeof SpecialDeliveryRoute
  TaxiRoute: typeof TaxiRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  WalletRoute: typeof WalletRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdsIdRoute: typeof AdsIdRoute
  AdsNewRoute: typeof AdsNewRoute
  JoinDriverRoute: typeof JoinDriverRoute
  JoinProviderRoute: typeof JoinProviderRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  StoresIdRoute: typeof StoresIdRoute
  AdsIndexRoute: typeof AdsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
  ServiceRequestsIndexRoute: typeof ServiceRequestsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
  ApiPublicAdImageSplatRoute: typeof ApiPublicAdImageSplatRoute
  ApiPublicPaymentsStripeRoute: typeof ApiPublicPaymentsStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-earnings': {
      id: '/driver-earnings'
      path: '/driver-earnings'
      fullPath: '/driver-earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-finance': {
      id: '/provider-finance'
      path: '/provider-finance'
      fullPath: '/provider-finance'
      preLoaderRoute: typeof ProviderFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-test-accounts': {
      id: '/setup-test-accounts'
      path: '/setup-test-accounts'
      fullPath: '/setup-test-accounts'
      preLoaderRoute: typeof SetupTestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-test-admin': {
      id: '/setup-test-admin'
      path: '/setup-test-admin'
      fullPath: '/setup-test-admin'
      preLoaderRoute: typeof SetupTestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-delivery': {
      id: '/special-delivery'
      path: '/special-delivery'
      fullPath: '/special-delivery'
      preLoaderRoute: typeof SpecialDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi': {
      id: '/taxi'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-phone': {
      id: '/verify-phone'
      path: '/verify-phone'
      fullPath: '/verify-phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/admin/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$id': {
      id: '/ads/$id'
      path: '/ads/$id'
      fullPath: '/ads/$id'
      preLoaderRoute: typeof AdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/new': {
      id: '/ads/new'
      path: '/ads/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/driver': {
      id: '/join/driver'
      path: '/join/driver'
      fullPath: '/join/driver'
      preLoaderRoute: typeof JoinDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/provider': {
      id: '/join/provider'
      path: '/join/provider'
      fullPath: '/join/provider'
      preLoaderRoute: typeof JoinProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests/': {
      id: '/service-requests/'
      path: '/service-requests'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof ServiceRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-image/$': {
      id: '/api/public/ad-image/$'
      path: '/api/public/ad-image/$'
      fullPath: '/api/public/ad-image/$'
      preLoaderRoute: typeof ApiPublicAdImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/stripe': {
      id: '/api/public/payments/stripe'
      path: '/api/public/payments/stripe'
      fullPath: '/api/public/payments/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CourierRoute: CourierRoute,
  DriverRoute: DriverRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProviderRoute: ProviderRoute,
  ProviderFinanceRoute: ProviderFinanceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupAdminRoute: SetupAdminRoute,
  SetupTestAccountsRoute: SetupTestAccountsRoute,
  SetupTestAdminRoute: SetupTestAdminRoute,
  SpecialDeliveryRoute: SpecialDeliveryRoute,
  TaxiRoute: TaxiRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  WalletRoute: WalletRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdsIdRoute: AdsIdRoute,
  AdsNewRoute: AdsNewRoute,
  JoinDriverRoute: JoinDriverRoute,
  JoinProviderRoute: JoinProviderRoute,
  OrdersIdRoute: OrdersIdRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  StoresIdRoute: StoresIdRoute,
  AdsIndexRoute: AdsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
  ServiceRequestsIndexRoute: ServiceRequestsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
  ApiPublicAdImageSplatRoute: ApiPublicAdImageSplatRoute,
  ApiPublicPaymentsStripeRoute: ApiPublicPaymentsStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
