INSERT INTO public.profession_categories (name, icon, sort_order, is_active)
SELECT v.name, v.icon, v.sort_order, true
FROM (VALUES
  ('فني أجهزة كهربائية','Plug',7),
  ('فني غسالات وثلاجات','Refrigerator',8),
  ('فني تلفزيونات وستلايت','Tv',9),
  ('فني كمبيوتر ولابتوب','Laptop',10),
  ('تصليح موبايلات','Smartphone',11),
  ('فني إنترنت وشبكات','Wifi',12),
  ('كاميرات مراقبة','Camera',13),
  ('فني مصاعد','Building2',14),
  ('فني مولدات','Bolt',15),
  ('فني طاقة شمسية','Sun',16),
  ('بنّاء','HardHat',17),
  ('حداد','Hammer',18),
  ('ألمنيوم وزجاج','Frame',19),
  ('جبس وديكور','Ruler',20),
  ('سيراميك وكاشي','Grid3x3',21),
  ('عزل أسطح',(('Umbrella')),22),
  ('فني جبسم بورد','Layers',23),
  ('نقاش سيارات','Brush',24),
  ('ميكانيك سيارات','Wrench',25),
  ('كهربائي سيارات','BatteryCharging',26),
  ('بنجرجي (تصليح إطارات)','CircleDot',27),
  ('غسل سيارات','Droplet',28),
  ('سحب ونقل سيارات','Truck',29),
  ('تصليح دراجات','Bike',30),
  ('نقل أثاث','Package',31),
  ('تنظيف مكاتب ومحلات','Sparkle',32),
  ('تنظيف خزانات','Waves',33),
  ('مكافحة حشرات','Bug',34),
  ('رفع نفايات','Trash2',35),
  ('تنسيق حدائق','Trees',36),
  ('بستنة وزراعة','Flower2',37),
  ('حلاق رجالي','Scissors',38),
  ('كوافير نسائي','Palette',39),
  ('خياط','Shirt',40),
  ('كوي وغسيل ملابس','Shirt',41),
  ('مصمم أظافر ومكياج','Gem',42),
  ('مدرس خصوصي','GraduationCap',43),
  ('تعليم قرآن','BookOpen',44),
  ('مدرب لياقة','Dumbbell',45),
  ('مترجم','Languages',46),
  ('مصور فوتوغرافي','Camera',47),
  ('تصميم غرافيك','Palette',48),
  ('تنظيم مناسبات','PartyPopper',49),
  ('طباخ ومناسف','ChefHat',50),
  ('حلويات وكيك','Cake',51),
  ('خدمة ضيافة','Utensils',52),
  ('ممرض منزلي','Syringe',53),
  ('علاج طبيعي','HeartPulse',54),
  ('رعاية كبار السن','Stethoscope',55),
  ('جليسة أطفال','Baby',56),
  ('محامي','Scale',57),
  ('محاسب','Calculator',58),
  ('استشارات أعمال','Briefcase',59),
  ('معاملات حكومية','FileText',60),
  ('فني أقفال','Key',61),
  ('فني ستائر وأثاث','Sofa',62),
  ('فني تمديدات غاز','Flame',63),
  ('فني مضخات ماء','Droplets',64)
) AS v(name, icon, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.profession_categories p
  WHERE p.name = v.name AND p.deleted_at IS NULL
);